import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>OnlyFakeNews - Your trusty site for fake news</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="max-w-xl mx-auto px-2 py-8  space-y-6">
				<div>
					<h1 className="text-3xl font-extrabold">OnlyFakenews</h1>
					<p className="text-sm my-1 ml-2">
						The{' '}
						<span className="text-white bg-black/50 rounded px-0.5">
							news app
						</span>{' '}
						for dummies
					</p>
				</div>{' '}
				<form className="grid">
					<input
						type="text"
						placeholder="search news article"
						className="border px-5 py-2 rounded"
					/>
				</form>
				<ul role="list" className="grid gap-4 odd">
					{[0, 1, 2, 3, 5, 6].map((n) => (
						<li
							className="px-3 py-4 space-y-4 border-b last:border-0"
							key={n}
						>
							<h2 className="font-bold text-xl">
								Lorem ipsum dolor sit.
							</h2>
							<p>
								Lorem ipsum dolor, sit amet consectetur
								adipisicing elit. Facere, sequi aperiam debitis,
								ab error in voluptas vel tenetur dolor et
								accusantium officia quae? Voluptates eveniet
								sequi cupiditate eius consequuntur saepe.
							</p>
							<div>
								<p>rehkmansa</p>
								<div>
									<p></p>
									<p></p>
								</div>
							</div>
						</li>
					))}
				</ul>
			</section>
		</>
	);
}
