import Head from 'next/head';
import { NewsAPIData } from './api/news';
import { Star } from '@/components/Icons';

const serverURL = process.env.APP_URL;

export default function Home({ news }: NewsAPIData) {
	return (
		<>
			<Head>
				<title>OnlyFakeNews - Your trusty site for fake news</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="max-w-xl mx-auto px-2 py-8  space-y-6">
				<div>
					<h1 className="text-3xl font-extrabold">OnlyFakenews</h1>
					<p className="text-sm my-1 ml-2">
						The{' '}
						<span className="text-white bg-black/50 rounded px-0.5">
							news app
						</span>{' '}
						for dummies
					</p>
				</div>{' '}
				<form className="grid">
					<input
						type="text"
						placeholder="search news article"
						className="border px-5 py-2 rounded"
					/>
				</form>
				<ul role="list" className="grid gap-4 odd">
					{news
						.slice(0, 10)
						.map(({ title, author, rating, excerpt }) => (
							<li
								className="px-3 py-4 space-y-4 border-b last:border-0 gap-4"
								key={title}
							>
								<div className="flex justify-between items-start">
									<h2 className="font-bold text-xl">
										{title}
									</h2>
									<p className="flex items-center gap-2">
										<Star
											fontSize={20}
											className="w-5 h-5"
										/>
										{rating.rating}
									</p>
								</div>
								<p>{excerpt}</p>
								<div>
									<p className="bg-black text-white rounded px-3 w-fit text-sm">
										{author.name}
									</p>
								</div>
							</li>
						))}
				</ul>
			</section>
		</>
	);
}

export async function getServerSideProps() {
	const url = serverURL + '/api/news';

	const res = await fetch(url);
	const data = await res.json();

	return {
		props: data,
	};
}
